version: '3'
services:
  api:
    build: ./api
    ports:
      - '5050:5050'
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    #volumes:
    #  - ./api:/app
  
    